# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lms.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'lms.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tlms.proto\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\".\n\rLoginResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\"\x1e\n\rLogoutRequest\x12\r\n\x05token\x18\x01 \x01(\t\" \n\x0eLogoutResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"8\n\x0bPostRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\"\x1e\n\x0cPostResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\")\n\nGetRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\"<\n\x0bGetResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x1d\n\ndata_items\x18\x02 \x03(\x0b\x32\t.DataItem\"\'\n\x08\x44\x61taItem\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t2\x9f\x01\n\x03LMS\x12&\n\x05Login\x12\r.LoginRequest\x1a\x0e.LoginResponse\x12)\n\x06Logout\x12\x0e.LogoutRequest\x1a\x0f.LogoutResponse\x12#\n\x04Post\x12\x0c.PostRequest\x1a\r.PostResponse\x12 \n\x03Get\x12\x0b.GetRequest\x1a\x0c.GetResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lms_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGINREQUEST']._serialized_start=13
  _globals['_LOGINREQUEST']._serialized_end=63
  _globals['_LOGINRESPONSE']._serialized_start=65
  _globals['_LOGINRESPONSE']._serialized_end=111
  _globals['_LOGOUTREQUEST']._serialized_start=113
  _globals['_LOGOUTREQUEST']._serialized_end=143
  _globals['_LOGOUTRESPONSE']._serialized_start=145
  _globals['_LOGOUTRESPONSE']._serialized_end=177
  _globals['_POSTREQUEST']._serialized_start=179
  _globals['_POSTREQUEST']._serialized_end=235
  _globals['_POSTRESPONSE']._serialized_start=237
  _globals['_POSTRESPONSE']._serialized_end=267
  _globals['_GETREQUEST']._serialized_start=269
  _globals['_GETREQUEST']._serialized_end=310
  _globals['_GETRESPONSE']._serialized_start=312
  _globals['_GETRESPONSE']._serialized_end=372
  _globals['_DATAITEM']._serialized_start=374
  _globals['_DATAITEM']._serialized_end=413
  _globals['_LMS']._serialized_start=416
  _globals['_LMS']._serialized_end=575
# @@protoc_insertion_point(module_scope)
